name: Weather API Call

on:
  push:
    branches: [ main ]

jobs:
  fetch-weather:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Call OpenWeather API
        run: |
          location="New York"
          curl "https://api.openweathermap.org/data/2.5/weather?q=${location}&units=imperial&appid=${{ secrets.OPENWEATHER_API_KEY }}"
